### ISSUE TITLE
Access to uninitialized memory is possible

### ISSUE THREAD

**Issue by ip1981** [jannisteunissen/ffhash#1]
Since [short-circuit evaluation](https://en.wikipedia.org/wiki/Short-circuit_evaluation) is not  guaranteed in Fortran, this and similar code may access uninitialized memory, i. e. `keys_equal(h%keys(i), key)` is evaluated unconditionally:
https://github.com/jannisteunissen/ffhash/blob/65746edae35798b86f5994f21b07b8735aa65987/ffhash_inc.f90#L102

**Comment by jannisteunissen** [comment]
Ah yes, indeed, let me look into a fix

**Comment by jannisteunissen** [comment]
This should be fixed by commit 5a51a56 
If you found this with some tool, could you check whether it is okay now?

**Comment by ip1981** [comment]
I was told about issues reported by Valgrind with Intel Fortran compiler (no versions or compiler options known), but I cannot replicate it with GFortran with various options and the examples provided.

**Comment by jannisteunissen** [comment]
Ah that makes sense, according to [this blog](https://www.scivision.dev/fortran-short-circuit-logic/) ifort and gcc differ in their short-circuit behavior. I don't have access to ifort at the moment, but the issue should be fixed. Thanks for reporting it!
