### ISSUE TITLE
unnecessary code duplication: simpler `reset` method

### ISSUE THREAD

**Issue by hennink** [jannisteunissen/ffhash#2]
Just browsing through the code, I noticed that the `reset` method can be simplified, which also avoids some code duplication:

In [ffhash_inc.f90](https://github.com/jannisteunissen/ffhash/blob/775518392cd7414caec26513f55fd420c6861866/ffhash_inc.f90#L361), it can simply be

```
  subroutine reset(h)
    class(ffh_t), intent(out) :: h
  end subroutine reset
```
The `intent(out)` means something like "loose all information", so `h` is automatically reset to its original state with its default values (like `h%max_load_factor = 0.7d0`).
This means you won't have to update `reset` when components get added to or removed from `ffh_t`.

**Comment by jannisteunissen** [comment]
Thanks for the suggestion, I was afraid of things becoming undefined, but looking at the standard (http://www.j3-fortran.org/doc/year/10/10-007.pdf) under 5.3.10, it says:

> The INTENT (OUT) attribute for a nonpointer dummy argument specifies that the dummy argument becomes undefined on invocation of the procedure, except for any subcomponents that are default-initialized (4.5.4.6) [...]

So I'll make this simplification!

**Comment by jannisteunissen** [comment]
Now fixed
